---
title: "Shark prioritization: analysis"
author: "Casey O'Hara"
date: "11/2/2020"
output: 
  html:
    code_folding: show
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
---

```{r setup}
library(tidyverse)
library(terra)
library(sf)
library(here)
library(rnaturalearth)
```
 
## Identify priority habitat for two sharks in Mozambican waters

Read in .csv files of silky shark and hammerhead shark habitat suitability.  Fill in empty cells with zero values.  Find average suitability.

```{r}
ocean_mask <- read_csv('_data/ocean_mask.csv')
suitability_data <- read_csv('_data/shark_suitability.csv')

silky <- suitability_data %>%
  filter(species == 'silky shark')

hammerhead <- suitability_data %>%
  filter(species == 'scalloped hammerhead')

### to find average, group all species by lat/long, and calculate 
### the mean suitability across the two shark species
average <- suitability_data %>%
  group_by(long, lat) %>%
  summarize(suitability = mean(suitability)) %>%
  mutate(species = 'average')
```

## Create Africa continent polygon

```{r}
data_r <- rast(average)
sf_use_s2(FALSE)
afr_sf <- rnaturalearth::ne_countries(continent = 'Africa', returnclass = 'sf') %>%
  st_crop(st_bbox(data_rast))
```

## Plot suitability

```{r}
plot_df <- bind_rows(silky, hammerhead, average)

ggplot() +
  geom_raster(data = plot_df, aes(x = long, y = lat, fill = suitability)) +
  geom_sf(data = afr_sf) +
  scale_fill_viridis_c() +
  facet_wrap(~ species) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(x = 'Longitude', y = 'Latitude')
```

